# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 旅するマルチポテンシャライト
description: > # this means to ignore newlines until "baseurl:"
  自由に旅をしながら情熱と意味を持って仕事を生み出すマルチポテンシャライト、起業家、ノマドワーカーたちを世界中で取材し発信するサイト。
keywords: > # this means to ignore newlines until "baseurl:"
  multipotnomad、マルチポテンシャライト、起業家、ノマドワーカー、ノマド、旅、仕事、就活、新卒、情熱、意味、生み出す、作り出す、世界、取材、動画。
url: "https://multipotnomad.github.io" # the base hostname & protocol for your site #footer built by link


# baseurl: ""
permalink: /:title/

#color scheme - Purple theme
color-1: '#555'
color-2: '#998e8e'

#Endless-River theme - remove the '#'
#color-1: '#155799'
#color-2: '#159957'

#footer icons
f: mizuki.kawano.96  # facebook username
t: multipotnomad  # twitter handle
i: mizuki._.kawano # instagram username
y: UCjEc3Ad6TFt9r2IFD0-46xg # youtube channel

# Build settings
markdown: kramdown
sass:
    style: compressed

#Other
analytics: 'UA-122836174-1'
# disqus-shortname: multipotnomad    #Disqus comments

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Adding front matter to static files
defaults:
  - scope:
      path: "dev/img"
    values:
      image: true
